### ISSUE TITLE
Posters enhancements todo

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1211]
- [x] remove "hanging orders" category, replace with archive of completed orders
- [x] mail fixes
  - [x] add number of bongs to mail if relevant
  - [x] date of event
  - [x] format timestamp nicely and localize it
- [x] error messages for more things
