### ISSUE TITLE
Tracking issue for: "Transfer Mailinglists to Django Model"

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2453]
It would be much easier to edit the mailinglists from the OW4's admin-panel, instead of using Google's, and from there automatically update the list on `online.ntnu.no/resourcecenter/mailinglists/`

- [x] Add models for the mailinglists #2445
- [ ] Make view-site in OWF
- [ ] Make the lists sync with Gsuite
- [ ] Remove the https://online.ntnu.no/resourcecenter/mailinglists/

**Comment by henrikhorluck** [comment]
Not how we should solve this
